import { artwar } from "../../data/artwar"
import { qc } from "../../data/book"
import { brevedad } from "../../data/brevedad"
import { cvc24h } from "../../data/cvc24h"



export const books = [
    { id: 0, title: 'Como un hombre piensa asi es su vida',base64:qc, author: 'James Allen', favorite: false, cover: 'https://images.booksense.com/images/664/729/9781544729664.jpg',resumen:'Para James Allen, nuestros pensamientos son las semillas de lo que ocurrirá en nuestras vidas. La mente humana puede compararse con un jardín y su cultivo es, al mismo tiempo, un trabajo y un camino espiritual que Allen nos presenta con verdadera maestría.' },
    { id: 1, title: 'Como vivir con veinticuatros horas al dia',base64:cvc24h, author: 'Arnold Bennet', favorite: false, cover: 'https://images.booksense.com/images/550/488/9798638488550.jpg',resumen:'Este libro te recuerda que tienes que vivir con veinticuatro horas diarias, dentro de las cuales debes prestar atención a tu salud, al placer, a la producción de dinero, a tus valores y a la evolución de tu alma inmortal, ¿podrás hacerlo? Académicos y estudiosos de diversas partes del globo terraqueo, han recalcado la importante contribución a la literatura que se puede encontrar en las páginas de este libro. Su aporte no se ha visto afectado con el pasar de los años y asegura ser base de conocimientos para las futuras generaciones.' },
    { id: 2, title: 'Confianza en uno mismo', author: 'Ralph Waldo Emerson', favorite: false, cover: 'https://www.elejandria.com/covers/Confianza_en_uno_mismo-Ralph_Waldo_Emerson-md.png',resumen:'Confianza en uno mismo es uno de los ensayos más emblemáticos de Emerson. Es una llamada a lo esencial de nosotros mismos como propuesta vital, que encarna y resume lo mejor de la filosofía de Emerson: su inconformismo, su vitalismo, su fe en el individuo y en la intuición como fuente de sabiduría.' },
    {id:3,title:'De la brevedad de la vida',base64:brevedad, author:'Seneca',cover:'https://images-na.ssl-images-amazon.com/images/I/51MLIpyLcoL._SX331_BO1,204,203,200_.jpg',resumen:'Sobre la brevedad de la vida es un diálogo a modo de lamento: no es que la vida sea corta, sino que nosotras la hacemos así malgastando el tiempo. El verdadero sabio disfruta del presente, recuerda el pasado y previene el futuro sin perderse en tediosos placeres y sin temer a la muerte.'},
    {id:4,title:'El arte de la guerra',author:'Sun Tzu',base64:artwar,cover:'https://kbimages1-a.akamaihd.net/9b1d5cb3-32bf-49af-b7a3-d2d88743c665/166/300/False/el-arte-de-la-guerra-45.jpg',resumen:'Descubre cómo las antiguas estrategias del militar chino Sun Tzu pueden aplicarse tanto en tu negocio como en tu vida personal, ayudando a la resolución de conflictos y al crecimiento profesional.'},
    {id:5,title:'El arte de ser feliz', author:'Schopenhauer',cover:'https://images-na.ssl-images-amazon.com/images/I/61uaWZIjG7L.jpg',resumen:'Se trata de encontrar reglas de conducta y de vida que nos ayuden a evitar las penurias y los golpes del destino, con la esperanza de que, si bien la felicidad perfecta es inalcanzable, podamos llegar a esa felicidad relativa que consiste en la ausencia del dolor.'},
    {id:6,title:'El juego de la vida y como jugarlo',author:'Florence scovel shinn', cover:'https://static.wikia.nocookie.net/biblioteca-virtual-de-literatura/images/2/23/El_juego_de_la_vida_y_c%C3%B3mo_jugarlo.jpg/revision/latest?cb=20170817035410&path-prefix=es',resumen:'nos enseñará cómo cada uno de nosotros puede cambiar sus condiciones y circunstancias si pone atención en lo que se desea y que tanto lo quiere.La vida, tomada como un juego, sigue las reglas de las enseñanzas metafísicas, con las cuales alcanzaremos la victoria.'},
    {id:7,title:'La ciencia de estar bien',author:'Wallas Wattles', cover:'https://images-na.ssl-images-amazon.com/images/I/412mbg8RhfL.jpg',resumen:'El secreto es simplemente la demostración de que el poder de la palabra, del pensamiento positivo, de la fuerza que tenemos dentro, es enorme y nos será dada cuando estemos verdaderamente preparados para recibirla.'},
    {id:8,title:'La ciencia de hacerse rico', author: 'Wallas Wattles', cover:'https://kbimages1-a.akamaihd.net/a67e5fd8-04a1-4141-a12d-886844245a6d/166/300/False/la-ciencia-de-hacerse-rico-17.jpg',resumen:'¿Sabías que existe un método científico para hacerse rico? Descubre cómo funciona esta ciencia y transforma tu vida financiera.'},
    {id:9,title:'Meditaciones',author:'Marco Aurelio',cover:'https://kbimages1-a.akamaihd.net/e69085d9-b354-4846-8bd3-6cf9d837ccf7/1200/1200/False/meditaciones-20.jpg',resumen:'“Meditaciones” fue el legado estoico que nos dejó Marco Aurelio. Una obra maestra en la que el emperador romano se escribía a sí mismo para forzarse a ser mejor ciudadano, mejor emperador y, sobre todo, mejor persona. De hecho, es con esta y no otra la intención con la que hay que leerlo.'}



]